filter: 
  excluded_paths: 
    - webapp/_lib/extlib/*
    - extras/*
    - docs/*
    - tests/*
    - webapp/plugins/twitter/extlib/*
    - webapp/plugins/twitterrealtime/extlib/*
    - webapp/plugins/facebook/extlib/*
tools: 
  php_code_sniffer: true
  php_cs_fixer: true
  php_hhvm: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
