RENAME TABLE ta_follows TO tt_follows;
RENAME TABLE ta_tweets TO tt_tweets;
RENAME TABLE ta_users TO tt_users;
RENAME TABLE ta_instances TO tt_instances;
RENAME TABLE ta_owners TO tt_owners;
RENAME TABLE ta_owner_instances TO tt_owner_instances;
RENAME TABLE ta_tweet_errors TO tt_tweet_errors;
RENAME TABLE ta_user_errors TO tt_user_errors;
RENAME TABLE ta_links TO tt_links;