-- Creating tu_session_data table with two fields: session_key and session_data
-- Using field session_key instead of key because key is a reserved word in MySQL

CREATE TABLE tu_session_data (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT 'Internal unique ID.',
  session_key varchar(32) NOT NULL COMMENT 'Stores the key generated by using md5(microtime().$_SERVER[REMOTE_ADDR])',
  session_data text NOT NULL COMMENT 'Stores user session data in serialized format.',
  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Session data.';