#!/bin/bash
cd `dirname $0`/../../
source ./extras/cron/config

if [ -f $crawllogarch ]; then
  echo "Log archive present... Skiping archival process"
else 
  echo "Starting Archival process"
  tar -cvjf $crawllogarch $crawllog 
  if [ -f $crawllogarch ]; then
    echo "Deleting logfile"
    rm $crawllog
    touch $crawllog
  else
    echo "WARNING: Archive not created - Logfile not deleted"
  fi
fi

calog_lines1=`set $(wc -l $crawllog) && echo $1`
$php $crawler
calog_lines2=`set $(wc -l $crawllog) && echo $1`
calog_lines_diff=$((calog_lines2-calog_lines1))
tail -n $calog_lines_diff $crawllog
