#!/bin/bash
cd `dirname $0`/../../
source ./extras/cron/config

# files for crawl_interval setting
PID=${logdir}/crawl.pid
LASTCRAWL=${logdir}/lastcrawl

## help me?
if [ "$1" == "-h" ]; then
  echo
  echo "usage: $0 [-v|-h]"
  echo
  echo "  -v verbose debugging"
  echo "  -h show this message"
  echo
  exit
fi

# debug me?
if [ "$1" == "-v" ]; then
  DEBUG=$1;
  echo "Debugging is on..."
fi

# archive logs
if [ -f $crawllogarch ]; then
  if test $DEBUG; then
    echo "Log archive present... Skipping archival process"
  fi
else 
  if [ -f $crawllog ]; then
    if test $DEBUG; then
      echo "Starting archival process"
    fi
    # this will supress the "tar: Removing leading `/’ from member names" message 
    TAR_LOG=`echo $crawllog | sed -e 's/^\///'`
    tar -cjf $crawllogarch -C / $TAR_LOG
    if [ -f $crawllogarch ]; then
      if test $DEBUG; then
        echo "Deleting old logfile"
      fi
      rm -f $crawllog
      touch $crawllog
    else
      if test $DEBUG; then
        echo "WARNING: Archive not created - Logfile not deleted"
      fi
      if test $DEBUG; then
        echo "Starting Archival process"
      fi
      tar -cjf $crawllogarch $crawllog 
      if [ -f $crawllogarch ]; then
        echo "Deleting logfile"
        rm $crawllog
        touch $crawllog
      else
        echo "WARNING: Archive not created - Logfile not deleted"
      fi
    fi
  fi
fi

# if we have a crawl interval set in our config, see if it is time to crawl,
# else ignore
if test $crawl_interval; then
  if [ -f $PID ]; then
    echo "Crawler pid file exists '${PID}', is the crawler process already running?"
    exit
  fi
  if [ -f $LASTCRAWL ]; then
    LASTRAN=`cat ${LASTCRAWL}`
    NOW=`date +%s`
    let SINCE=($NOW - $LASTRAN)
    let INTERVAL=($crawl_interval \* 60) 
    if [ "$SINCE" -lt $INTERVAL ]; then
      if test $DEBUG; then
        echo "Cron has run within the past $crawl_interval minutes, exiting"
      fi
      exit
    fi
  else
    if test $DEBUG; then
      echo "${LASTCRAWL} not found, first time running the crawler?"
    fi
  fi
  echo $! > $PID
fi

#let's run our crawler...
if [ ! -f $crawllog ]; then
	touch $crawllog
fi
calog_lines1=`set $(wc -l $crawllog) && echo $1`
cd $thinkup/webapp/crawler
export THINKUP_PASSWORD=$thinkup_password
$php $crawler $thinkup_username
calog_lines2=`set $(wc -l $crawllog) && echo $1`
calog_lines_diff=$((calog_lines2-calog_lines1))
if test $DEBUG; then
  tail -n $calog_lines_diff $crawllog
fi

# if we have a crawl interval set
# set our last run timestamp and clean up pid file
if test crawl_interval; then
  # set last crawl finish time
  date +%s > ${LASTCRAWL}
  rm -f ${PID}
fi

