#!/bin/bash
cd `dirname $0`/..
source ./scripts/autodeploy-conf

scp -r common/* $username@$server:$remote_common
scp -r crawler/* $username@$server:$remote_crawler
scp -r cron/* $username@$server:$remote_cron
