#!/bin/bash
cd `dirname $0`/../..
source ./extras/scripts/autodeploy-conf

scp -r common/* $username@$server:$remote_common
scp -r crawler/* $username@$server:$remote_crawler
scp -r webapp/* $username@$server:$remote_webapp
scp -r extras/* $username@$server:$remote_extras
