#! /bin/bash

cp -R thinkup/webapp build/.
cp -R thinkup/COPYING build/webapp/.
cp -R thinkup/README.md build/webapp/.
mv build/webapp build/thinkup
rm -rf build/thinkup/_lib/view/compiled_view/*.tpl.php
rm -rf build/thinkup/_lib/view/compiled_view/cache/*.tpl
rm -rf build/thinkup/_lib/extlib/simpletest/
rm -rf build/thinkup/plugins/*/tests/
rm build/thinkup/config.inc.php
cd build
zip -r thinkup.zip thinkup 
zip -d thinkup.zip __MACOSX* *.DS_Store 
rm -rf thinkup 
